# migrations/script.py.mako
"""Initial migration

Revision ID: ab38ebda9dca
Revises: 
Create Date: 2025-04-22 23:47:13.666622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab38ebda9dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('routing_strategy', sa.String(length=20), nullable=False),
    sa.Column('dial_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_user_campaign_name')
    )
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_user_id'), 'campaigns', ['user_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_identifier', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_client_identifier'), 'clients', ['client_identifier'], unique=True)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_table('dids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dids_number'), 'dids', ['number'], unique=True)
    op.create_index(op.f('ix_dids_status'), 'dids', ['status'], unique=False)
    op.create_index(op.f('ix_dids_user_id'), 'dids', ['user_id'], unique=False)
    op.create_table('campaign_client_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('total_calls_allowed', sa.Integer(), nullable=True),
    sa.Column('current_total_calls', sa.Integer(), nullable=False),
    sa.Column('forwarding_priority', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_client_settings_campaign_id'), 'campaign_client_settings', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_client_settings_client_id'), 'campaign_client_settings', ['client_id'], unique=False)
    op.create_index(op.f('ix_campaign_client_settings_forwarding_priority'), 'campaign_client_settings', ['forwarding_priority'], unique=False)
    op.create_index(op.f('ix_campaign_client_settings_status'), 'campaign_client_settings', ['status'], unique=False)
    op.create_table('campaign_dids',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('did_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['did_id'], ['dids.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id', 'did_id')
    )
    op.create_table('pjsip_aors',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('max_contacts', sa.Integer(), nullable=True),
    sa.Column('qualify_frequency', sa.Integer(), nullable=True),
    sa.Column('config_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('pjsip_auths',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('realm', sa.String(length=80), nullable=True),
    sa.Column('config_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('pjsip_endpoints',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=40), nullable=True),
    sa.Column('aors', sa.String(length=200), nullable=True),
    sa.Column('auth', sa.String(length=40), nullable=True),
    sa.Column('context', sa.String(length=80), nullable=False),
    sa.Column('disallow', sa.String(length=200), nullable=True),
    sa.Column('allow', sa.String(length=200), nullable=True),
    sa.Column('direct_media', sa.String(length=10), nullable=True),
    sa.Column('outbound_auth', sa.String(length=40), nullable=True),
    sa.Column('from_user', sa.String(length=80), nullable=True),
    sa.Column('from_domain', sa.String(length=80), nullable=True),
    sa.Column('callerid', sa.String(length=80), nullable=True),
    sa.Column('config_updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('did_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('campaign_client_setting_id', sa.Integer(), nullable=True),
    sa.Column('incoming_did_number', sa.String(length=50), nullable=False),
    sa.Column('caller_id_num', sa.String(length=50), nullable=True),
    sa.Column('caller_id_name', sa.String(length=100), nullable=True),
    sa.Column('timestamp_start', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('timestamp_answered', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('timestamp_end', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('billsec_seconds', sa.Integer(), nullable=True),
    sa.Column('call_status', sa.String(length=50), nullable=False),
    sa.Column('hangup_cause_code', sa.Integer(), nullable=True),
    sa.Column('hangup_cause_text', sa.String(length=50), nullable=True),
    sa.Column('asterisk_uniqueid', sa.String(length=50), nullable=True),
    sa.Column('asterisk_linkedid', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_client_setting_id'], ['campaign_client_settings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['did_id'], ['dids.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_asterisk_linkedid'), 'call_logs', ['asterisk_linkedid'], unique=False)
    op.create_index(op.f('ix_call_logs_asterisk_uniqueid'), 'call_logs', ['asterisk_uniqueid'], unique=True)
    op.create_index(op.f('ix_call_logs_call_status'), 'call_logs', ['call_status'], unique=False)
    op.create_index(op.f('ix_call_logs_campaign_id'), 'call_logs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_call_logs_client_id'), 'call_logs', ['client_id'], unique=False)
    op.create_index(op.f('ix_call_logs_did_id'), 'call_logs', ['did_id'], unique=False)
    op.create_index(op.f('ix_call_logs_incoming_did_number'), 'call_logs', ['incoming_did_number'], unique=False)
    op.create_index(op.f('ix_call_logs_timestamp_start'), 'call_logs', ['timestamp_start'], unique=False)
    op.create_index(op.f('ix_call_logs_user_id'), 'call_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_user_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_timestamp_start'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_incoming_did_number'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_did_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_client_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_campaign_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_call_status'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_asterisk_uniqueid'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_asterisk_linkedid'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_table('pjsip_endpoints')
    op.drop_table('pjsip_auths')
    op.drop_table('pjsip_aors')
    op.drop_table('campaign_dids')
    op.drop_index(op.f('ix_campaign_client_settings_status'), table_name='campaign_client_settings')
    op.drop_index(op.f('ix_campaign_client_settings_forwarding_priority'), table_name='campaign_client_settings')
    op.drop_index(op.f('ix_campaign_client_settings_client_id'), table_name='campaign_client_settings')
    op.drop_index(op.f('ix_campaign_client_settings_campaign_id'), table_name='campaign_client_settings')
    op.drop_table('campaign_client_settings')
    op.drop_index(op.f('ix_dids_user_id'), table_name='dids')
    op.drop_index(op.f('ix_dids_status'), table_name='dids')
    op.drop_index(op.f('ix_dids_number'), table_name='dids')
    op.drop_table('dids')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_client_identifier'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_campaigns_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###